### ISSUE TITLE
Translated text should not be treated as error when it is same as the original.

### ISSUE THREAD

**Issue by b123400** [gpolak/FGTranslator#18]
A translation is considered as errored when the source is (somehow) same as the target, according to the code here: https://github.com/gpolak/FGTranslator/blob/master/FGTranslator/FGTranslator.m#L455-L464

This is quite wrong considering the following cases:

"你好" (Traditional Chinese) -> "你好" (Simplified Chinese)
"ballet" (English) -> "ballet" (French)
"貴族" (Japanses) -> "貴族" (Traditional Chinese)

May I ask why is it designed like this?

**Comment by gpolak** [comment]
This was done because in some cases the translate engine (Bing or Google) is not able to translate a string, yet returns a success and the "translated" string, which is just an original with extra spaces.

In the case above, if the translation fails because the result is the same, I just show the original text, which is correct. I agree that this is somewhat confusing. Thoughts on improving it?

**Comment by b123400** [comment]
Um... I'd say that kind of translations are not failure, just like `iPhone` is `iPhone` in every language, not because we cannot translate it, but because we don't need to translate it. Is there any example that you think is a "failed" translation?

**Comment by gpolak** [comment]
I agree with you that the current behavior doesn't make sense and should be changed. We still need to handle the weird case I mentioned above. I'll see if I can find an example where that happens. Thanks for looking into this!

**Comment by b123400** [comment]
You are welcome :)
I somehow think we should just leave it alone, give up handling this case.
It would be nice if we can solve the problem, but if we don't have a good solution, we should let the users (the developers who use this library) to handle it.

**Comment by gpolak** [comment]
Sounds good. I'll leave this issue open to track it.

**Comment by b123400** [comment]
Oops, sorry for my misleading comment. By "give up handling this case", I mean we should not handle the case that "translation server returns similar result" specially. Which means, we should treat it as a successful translation, just like every other translations. So my pull request should be accepted.

**Comment by gpolak** [comment]
The issue here is with incorrect source language specification.

For example if the sentence is "hello" and I set the source language to french (wrong), and destination language as something else (eg. German) , then Google Translate returns 200 and the result as "Hello" - same string but in uppercase. This is clearly wrong.

In this case FGTranslator automatically repeats the same request, but forces Google Translate to guess the source language, which usually gets it right.

The reason for this is that in an app you typically specify the source language based on the user's keyboard or locale. However this doesn't stop them typing in a different language (usually English), and this can throw off the translator.

**Comment by b123400** [comment]
How about treat it as an error only when `preferSourceGuess` is YES?

Not sure if I am missing something, but I cannot find any retry-related code in the repo, where is that logic?

**Comment by gpolak** [comment]
Hmm, you know what? You're right!

I had the retry in the original code but then I refactored it to prefer source guess instead and forgot this was still there. PR approved, thanks!
